In [103]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [104]:
df = pd.read_csv("Nutrientfilefinal.csv")
df

,Public Food Key,Classification,Food Name,"Energy with dietary fibre, equated \n(kJ)",Moisture (water) \n(g),Protein \n(g),Nitrogen \n(g),"Fat, total \n(g)",Total dietary fibre \n(g),Glucose \n(g),...,Potassium (K) \n(mg),Sodium (Na) \n(mg),Zinc (Zn) \n(mg),Cobalamin (B12) \n(ug),Folic acid \n(ug),Vitamin C \n(mg),Vitamin E \n(mg),"Total saturated fatty acids, equated \n(g)",Caffeine \n(mg),Cholesterol \n(mg)
0,F002258,31302.0,"Cardamom seed, dried, ground","1,236",8.3,10.8,1.72,6.7,28.0,NaN,...,"1,119",18,7.47,0.0,0,21,2.85,2.20,0,0
1,F002893,31302.0,"Chilli (chili), dried, ground","1,280",10.8,13.4,2.14,14.3,34.8,NaN,...,"1,950","2,867",4.30,0.0,0,1,38.14,2.06,0,0
2,F002963,31302.0,"Cinnamon, dried, ground","1,004",10.6,4.0,0.64,1.2,53.1,NaN,...,431,10,1.83,0.0,0,4,2.32,0.62,0,0
3,F002970,31302.0,"Cloves, dried, ground","1,389",9.9,6.0,0.96,13.0,33.9,NaN,...,"1,020",277,2.32,0.0,0,0,8.82,5.49,0,0
4,F003190,31302.0,"Coriander seed, dried, ground","1,344",8.9,12.4,1.98,17.8,41.9,NaN,...,"1,267",35,4.70,0.0,0,21,0.91,1.03,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1611,F009774,24702.0,"Zucchini, green skin, fresh, unpeeled, fried, ...",92,92.6,1.3,0.20,0.4,1.6,1.1,...,268,1,0.47,0.0,0,29,0.70,0.00,0,0
1612,F009773,24702.0,"Zucchini, green skin, fresh, unpeeled, boiled,...",77,93.8,1.1,0.17,0.4,1.3,1.0,...,201,1,0.37,0.0,0,21,0.59,0.00,0,0
1613,F009766,24702.0,"Zucchini, golden, fresh, unpeeled, raw",78,94.1,2.2,0.35,0.3,1.0,0.5,...,230,1,0.70,0.0,0,30,0.52,0.00,0,0
1614,F009765,24702.0,"Zucchini, golden, fresh, unpeeled, fried, no a...",111,91.6,3.1,0.50,0.4,1.4,0.7,...,328,1,1.00,0.0,0,36,0.70,0.00,0,0
1615,F009764,24702.0,"Zucchini, golden, fresh, unpeeled, boiled, dra...",93,93.0,2.6,0.42,0.4,1.2,0.6,...,246,1,0.79,0.0,0,27,0.59,0.00,0,0

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1616 entries, 0 to 1615
Data columns (total 31 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Public Food Key                                      1616 non-null   object
 1   Classification                                       1614 non-null   float64
 2   Food Name                                            1616 non-null   object
 3   Energy with dietary fibre, equated
(kJ)             1616 non-null   object
 4   Moisture (water)
(g)                                1616 non-null   float64
 5   Protein
(g)                                         1616 non-null   float64
 6   Nitrogen
(g)                                        1616 non-null   float64
 7   Fat, total
(g)                                      1616 non-null   float64
 8   Total dietary fibre
(g)                             1616 non-null   float64
 9   Glucose
(g)                                         1424 non-null   float64
 10  Added sugars (g)                                     1616 non-null   float64
 11  Free sugars
(g)                                     1616 non-null   float64
 12  Starch
(g)                                          1616 non-null   float64
 13  Available carbohydrate, without sugar alcohols
(g)  1616 non-null   float64
 14  Available carbohydrate, with sugar alcohols
(g)     1616 non-null   float64
 15  Calcium (Ca)
(mg)                                   1616 non-null   object
 16  Copper (Cu)
(mg)                                    1255 non-null   float64
 17  Iodine (I)
(ug)                                     1616 non-null   object
 18  Iron (Fe)
(mg)                                      1616 non-null   float64
 19  Magnesium (Mg)
(mg)                                 1616 non-null   int64
 20  Phosphorus (P)
(mg)                                 1616 non-null   object
 21  Potassium (K)
(mg)                                  1616 non-null   object
 22  Sodium (Na)
(mg)                                    1616 non-null   object
 23  Zinc (Zn)
(mg)                                      1616 non-null   float64
 24  Cobalamin (B12)
(ug)                                1616 non-null   float64
 25  Folic acid
(ug)                                     1616 non-null   object
 26  Vitamin C
(mg)                                      1616 non-null   int64
 27  Vitamin E
(mg)                                      1616 non-null   float64
 28  Total saturated fatty acids, equated
(g)            1616 non-null   float64
 29  Caffeine
(mg)                                       1616 non-null   object
 30  Cholesterol
(mg)                                    1616 non-null   object
dtypes: float64(18), int64(2), object(11)
memory usage: 391.5+ KB

In [106]:
df.head(2)

,Public Food Key,Classification,Food Name,"Energy with dietary fibre, equated \n(kJ)",Moisture (water) \n(g),Protein \n(g),Nitrogen \n(g),"Fat, total \n(g)",Total dietary fibre \n(g),Glucose \n(g),...,Potassium (K) \n(mg),Sodium (Na) \n(mg),Zinc (Zn) \n(mg),Cobalamin (B12) \n(ug),Folic acid \n(ug),Vitamin C \n(mg),Vitamin E \n(mg),"Total saturated fatty acids, equated \n(g)",Caffeine \n(mg),Cholesterol \n(mg)
0,F002258,31302.0,"Cardamom seed, dried, ground","1,236",8.3,10.8,1.72,6.7,28.0,NaN,...,"1,119",18,7.47,0.0,0,21,2.85,2.20,0,0
1,F002893,31302.0,"Chilli (chili), dried, ground","1,280",10.8,13.4,2.14,14.3,34.8,NaN,...,"1,950","2,867",4.30,0.0,0,1,38.14,2.06,0,0

In [107]:
df.shape

(1616, 31)

In [108]:
df.isnull().sum()

Public Food Key                                           0
Classification                                            2
Food Name                                                 0
Energy with dietary fibre, equated \n(kJ)                 0
Moisture (water) \n(g)                                    0
Protein \n(g)                                             0
Nitrogen \n(g)                                            0
Fat, total \n(g)                                          0
Total dietary fibre \n(g)                                 0
Glucose \n(g)                                           192
Added sugars (g)                                          0
Free sugars \n(g)                                         0
Starch \n(g)                                              0
Available carbohydrate, without sugar alcohols \n(g)      0
Available carbohydrate, with sugar alcohols \n(g)         0
Calcium (Ca) \n(mg)                                       0
Copper (Cu) \n(mg)                                      361
Iodine (I) \n(ug)                                         0
Iron (Fe) \n(mg)                                          0
Magnesium (Mg) \n(mg)                                     0
Phosphorus (P) \n(mg)                                     0
Potassium (K) \n(mg)                                      0
Sodium (Na) \n(mg)                                        0
Zinc (Zn) \n(mg)                                          0
Cobalamin (B12) \n(ug)                                    0
Folic acid \n(ug)                                         0
Vitamin C \n(mg)                                          0
Vitamin E \n(mg)                                          0
Total saturated fatty acids, equated \n(g)                0
Caffeine \n(mg)                                           0
Cholesterol \n(mg)                                        0
dtype: int64

In [109]:
# This will give what %tage of each column's data is null
# In our case, 0 %tage of each column's data is null
# Which means no data Filling is needed
p = df.isnull().sum()
p = p/len(df)*100
p

Public Food Key                                          0.000000
Classification                                           0.123762
Food Name                                                0.000000
Energy with dietary fibre, equated \n(kJ)                0.000000
Moisture (water) \n(g)                                   0.000000
Protein \n(g)                                            0.000000
Nitrogen \n(g)                                           0.000000
Fat, total \n(g)                                         0.000000
Total dietary fibre \n(g)                                0.000000
Glucose \n(g)                                           11.881188
Added sugars (g)                                         0.000000
Free sugars \n(g)                                        0.000000
Starch \n(g)                                             0.000000
Available carbohydrate, without sugar alcohols \n(g)     0.000000
Available carbohydrate, with sugar alcohols \n(g)        0.000000
Calcium (Ca) \n(mg)                                      0.000000
Copper (Cu) \n(mg)                                      22.339109
Iodine (I) \n(ug)                                        0.000000
Iron (Fe) \n(mg)                                         0.000000
Magnesium (Mg) \n(mg)                                    0.000000
Phosphorus (P) \n(mg)                                    0.000000
Potassium (K) \n(mg)                                     0.000000
Sodium (Na) \n(mg)                                       0.000000
Zinc (Zn) \n(mg)                                         0.000000
Cobalamin (B12) \n(ug)                                   0.000000
Folic acid \n(ug)                                        0.000000
Vitamin C \n(mg)                                         0.000000
Vitamin E \n(mg)                                         0.000000
Total saturated fatty acids, equated \n(g)               0.000000
Caffeine \n(mg)                                          0.000000
Cholesterol \n(mg)                                       0.000000
dtype: float64

In [110]:
df['Classification'].unique()

array([3.1302e+04, 3.1301e+04, 3.1303e+04, 3.1501e+04, 3.1502e+04,
       1.2103e+04, 2.4102e+04, 3.1401e+04, 3.1101e+04, 2.9101e+04,
       2.9102e+04, 2.9301e+04, 2.9401e+04, 2.9201e+04, 2.9202e+04,
       2.9203e+04, 3.0105e+04, 3.0104e+04, 1.1804e+04, 1.1802e+04,
       1.1803e+04, 1.1801e+04, 1.1205e+04, 1.1201e+04, 1.1203e+04,
       1.1209e+04, 1.1208e+04, 1.1202e+04, 1.1403e+04, 1.1401e+04,
       1.1307e+04, 1.1301e+04, 2.2203e+04, 1.1702e+04, 1.1505e+04,
       1.1503e+04, 1.1504e+04, 1.1603e+04, 1.1501e+04, 1.1502e+04,
       2.9505e+04, 1.1101e+04, 1.1103e+04, 1.1701e+04, 1.3204e+04,
       1.3202e+04, 1.3201e+04, 1.3205e+04, 1.3203e+04, 1.3200e+02,
       1.3101e+04, 1.3102e+04, 1.3105e+04,        nan, 1.3106e+04,
       1.3104e+04, 1.2201e+04, 1.2302e+04, 1.2207e+04, 1.2202e+04,
       1.2203e+04, 1.2304e+04, 1.2204e+04, 1.2305e+04, 1.2307e+04,
       1.2213e+04, 1.2210e+04, 1.2306e+04, 1.3606e+04, 1.2301e+04,
       1.1805e+04, 1.2501e+04, 1.2502e+04, 1.2512e+04, 1.2515e+04,
       1.2513e+04, 1.2511e+04, 1.2503e+04, 1.2504e+04, 1.2509e+04,
       1.2506e+04, 1.2505e+04, 1.2514e+04, 1.3303e+04, 1.3306e+04,
       1.3301e+04, 1.3302e+04, 1.3605e+04, 1.3304e+04, 1.3601e+04,
       1.3602e+04, 1.3305e+04, 1.3307e+04, 1.2101e+04, 1.2601e+04,
       1.2102e+04, 1.3511e+04, 2.5201e+04, 1.2104e+04, 1.3506e+04,
       1.3505e+04, 1.3503e+04, 1.3501e+04, 1.2403e+04, 1.2401e+04,
       1.2402e+04, 1.3509e+04, 1.3401e+04, 1.3405e+04, 1.3406e+04,
       1.3402e+04, 1.3403e+04, 2.3303e+04, 2.3301e+04, 2.3102e+04,
       2.3101e+04, 2.3503e+04, 2.3302e+04, 2.3103e+04, 2.3109e+04,
       1.5504e+04, 2.3107e+04, 1.8701e+04, 2.3104e+04, 2.3108e+04,
       2.3305e+04, 2.2202e+04, 3.1102e+04, 1.9401e+04, 1.9403e+04,
       1.9405e+04, 1.9402e+04, 1.9406e+04, 1.9407e+04, 2.0301e+04,
       1.9301e+04, 1.9305e+04, 1.9303e+04, 1.9304e+04, 1.9501e+04,
       1.9505e+04, 2.7303e+04, 1.9101e+04, 1.9102e+04, 1.9103e+04,
       1.9104e+04, 1.9105e+04, 1.9803e+04, 1.9106e+04, 1.9107e+04,
       3.2102e+04, 1.9602e+04, 1.9701e+04, 1.9204e+04, 1.9201e+04,
       1.9205e+04, 1.9207e+04, 1.9209e+04, 1.9208e+04, 2.0106e+04,
       2.0101e+04, 2.0102e+04, 2.0104e+04, 2.0601e+04, 2.0000e+01,
       2.0501e+04, 2.0502e+04, 1.4101e+04, 1.4102e+04, 1.4201e+04,
       1.4301e+04, 1.4306e+04, 1.4303e+04, 1.4304e+04, 1.4402e+04,
       1.4401e+04, 1.4502e+04, 1.4501e+04, 1.7101e+04, 1.7102e+04,
       1.7201e+04, 1.6101e+04, 1.6802e+04, 1.4676e+04, 1.6403e+04,
       1.6404e+04, 1.6501e+04, 1.6201e+04, 1.6702e+04, 1.6303e+04,
       1.6801e+04, 1.6504e+04, 1.6503e+04, 1.6601e+04, 1.6302e+04,
       1.6804e+04, 1.6105e+04, 1.6304e+04, 1.6505e+04, 1.6401e+04,
       1.6301e+04, 1.6402e+04, 1.6103e+04, 1.6104e+04, 1.6502e+04,
       1.6202e+04, 2.4502e+04, 2.5101e+04, 2.5102e+04, 2.4501e+04,
       1.8101e+04, 1.8104e+04, 1.8102e+04, 1.8202e+04, 1.8103e+04,
       1.8301e+04, 1.8903e+04, 1.8302e+04, 1.8303e+04, 3.4101e+04,
       1.8300e+02, 1.8011e+04, 1.8201e+04, 1.8401e+04, 1.8601e+04,
       1.8606e+04, 1.8605e+04, 1.8502e+04, 1.8602e+04, 1.8603e+04,
       1.8501e+04, 1.8503e+04, 2.2204e+04, 2.2201e+04, 2.2102e+04,
       2.2101e+04, 1.5101e+04, 1.5501e+04, 1.5302e+04, 1.5202e+04,
       1.5201e+04, 1.5401e+04, 1.5102e+04, 2.8302e+04, 2.8201e+04,
       2.8202e+04, 2.8301e+04, 2.8303e+04, 2.8304e+04, 2.6201e+04,
       2.6301e+04, 2.6401e+04, 2.6202e+04, 2.6101e+04, 2.1201e+04,
       2.1301e+04, 2.1202e+04, 2.8102e+04, 2.8103e+04, 2.8101e+04,
       2.8100e+02, 2.3201e+04, 2.7201e+04, 2.7204e+04, 2.7102e+04,
       2.7101e+04, 2.8401e+04, 2.7301e+04, 2.4402e+04, 2.4302e+04,
       2.4705e+04, 2.4403e+04, 2.4201e+04, 2.4202e+04, 2.4301e+04,
       2.4704e+04, 2.4401e+04, 2.4801e+04, 2.4802e+04, 2.3202e+04,
       2.4803e+04, 2.4703e+04, 2.4101e+04, 2.4103e+04, 2.4701e+04,
       2.4404e+04, 2.4503e+04, 2.4702e+04, 2.4001e+04, 2.4601e+04,
       2.4602e+04])