In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns

In [77]:
df = pd.read_csv("Nfacts.csv")
df

,Food,Grams,Calories,Protein,Fat,Sat.Fat,Fiber,Carbs,Category
0,Cows' milk,976,660,32,40,36,0,48,Dairy products
1,Milk skim,984,360,36,t,t,0,52,Dairy products
2,Buttermilk,246,127,9,5,4,0,13,Dairy products
3,"Evaporated, undiluted",252,345,16,20,18,0,24,Dairy products
4,Fortified milk,"1,419","1,373",89,42,23,1.4,119,Dairy products
...,...,...,...,...,...,...,...,...,...
330,Fruit-flavored soda,346,161,0,0,0,0,42,"Drinks,Alcohol, Beverages"
331,Ginger ale,346,105,0,0,0,0,28,"Drinks,Alcohol, Beverages"
332,Root beer,346,140,0,0,0,0,35,"Drinks,Alcohol, Beverages"
333,Coffee,230,3,t,0,0,0,1,"Drinks,Alcohol, Beverages"
334,Tea,230,4,0,t,0,0,1,"Drinks,Alcohol, Beverages"

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335 entries, 0 to 334
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Food      335 non-null    object
 1   Grams     335 non-null    object
 2   Calories  334 non-null    object
 3   Protein   335 non-null    object
 4   Fat       335 non-null    object
 5   Sat.Fat   333 non-null    object
 6   Fiber     335 non-null    object
 7   Carbs     335 non-null    object
 8   Category  335 non-null    object
dtypes: object(9)
memory usage: 23.7+ KB

In [79]:
df.head()

,Food,Grams,Calories,Protein,Fat,Sat.Fat,Fiber,Carbs,Category
0,Cows' milk,976,660,32,40,36,0,48,Dairy products
1,Milk skim,984,360,36,t,t,0,52,Dairy products
2,Buttermilk,246,127,9,5,4,0,13,Dairy products
3,"Evaporated, undiluted",252,345,16,20,18,0,24,Dairy products
4,Fortified milk,"1,419","1,373",89,42,23,1.4,119,Dairy products

In [80]:
df.shape

(335, 9)

In [81]:
df.isnull().sum()

Food        0
Grams       0
Calories    1
Protein     0
Fat         0
Sat.Fat     2
Fiber       0
Carbs       0
Category    0
dtype: int64

In [82]:
df['Category'].unique()

array(['Dairy products', 'Fats, Oils, Shortenings', 'Meat, Poultry',
       'Fish, Seafood', 'Vegetables A-E', 'Vegetables F-P',
       'Vegetables R-Z', 'Fruits A-F', 'Fruits G-P', 'Fruits R-Z',
       'Breads, cereals, fastfood,grains', 'Soups', 'Desserts, sweets',
       'Jams, Jellies', 'Seeds and Nuts', 'Drinks,Alcohol, Beverages'],
      dtype=object)

In [83]:
df = df[df["Category"] == "Dairy products"]

In [84]:
df.head()

,Food,Grams,Calories,Protein,Fat,Sat.Fat,Fiber,Carbs,Category
0,Cows' milk,976,660,32,40,36,0,48,Dairy products
1,Milk skim,984,360,36,t,t,0,52,Dairy products
2,Buttermilk,246,127,9,5,4,0,13,Dairy products
3,"Evaporated, undiluted",252,345,16,20,18,0,24,Dairy products
4,Fortified milk,"1,419","1,373",89,42,23,1.4,119,Dairy products

In [91]:
### Split the data into independent and dependent features

X = df.iloc[:,1:8]
y = df.iloc[:,4]

In [92]:
X

    Grams Calories Protein Fat Sat.Fat Fiber Carbs
0     976      660      32  40      36     0    48
1     984      360      36   t       t     0    52
2     246      127       9   5       4     0    13
3     252      345      16  20      18     0    24
4   1,419    1,373      89  42      23   1.4   119
5     103      515      27  28      24     0    39
6      85      290      30   t       t     0    42
7      85      290      30   t       t     1    42
8     244      165       8  10       8     0    11
9     540      690      24  24      22     0    70
10    252      235       8  11      10     0    26
11    250      128      18   4       3     1    13
12    248      275       9  10       9     0    40
13    248      285      13  14      11     0    28
14    188      300       6  18      16     0    29
15    190      275       9  10       9     0    32
16    120      170       4  15      13     0     5
17    119      430       2  44      27     1     3
18    225      240      30  11      10     0     6
19    225      195      38   t       t     0     6
20     17       70       4   6       5     0     t
21     56      226      14  19      17     0     1
22     28      105       2  11      10     0     1
23     28      105       7   9       8     0     t
24     28      105       6   9       8     0     t
25     28      105       7   8       7     0     t
26    100      150      12  12      10     0     t
27    128      220      13  16      14     0     1

In [93]:
y

0     40
1      t
2      5
3     20
4     42
5     28
6      t
7      t
8     10
9     24
10    11
11     4
12    10
13    14
14    18
15    10
16    15
17    44
18    11
19     t
20     6
21    19
22    11
23     9
24     9
25     8
26    12
27    16
Name: Fat, dtype: object

In [95]:
from sklearn.linear_model import LogisticRegression

In [96]:
classifier = LogisticRegression()

In [98]:
classifier

LogisticRegression()

In [99]:
sns.pairplot(df,hue='Grams')

ValueError: No variables found for grid columns.